from __future__ import annotations

from dataclasses import dataclass

from nightfall_mix.config import PresetName


@dataclass(frozen=True)
class PresetSpec:
    name: PresetName
    hpf_hz: float
    lpf_hz: float
    lpf_q: float
    saturation_scale: float
    tape_drive: float
    tape_bias: float
    softclip_threshold: float
    compression_scale: float
    comp_ratio: float
    comp_threshold_db: float
    comp_attack_ms: float
    comp_release_ms: float
    bit_depth: int
    sample_rate_reduction_hz: float
    wow_rate_hz: float
    wow_depth: float
    flutter_rate_hz: float
    flutter_depth: float
    stereo_width: float
    vinyl_noise_level_db: float
    tape_hiss_level_db: float
    atmosphere_volume_db: float
    atmosphere_stereo_width: float
    atmosphere_lpf_hz: float


PRESETS: dict[PresetName, PresetSpec] = {
    PresetName.tokyo_cassette: PresetSpec(
        name=PresetName.tokyo_cassette,
        hpf_hz=38.0,
        lpf_hz=9000.0,
        lpf_q=0.78,
        saturation_scale=1.02,
        tape_drive=1.08,
        tape_bias=-0.05,
        softclip_threshold=0.982,
        compression_scale=0.95,
        comp_ratio=2.1,
        comp_threshold_db=-18.0,
        comp_attack_ms=24.0,
        comp_release_ms=220.0,
        bit_depth=14,
        sample_rate_reduction_hz=36000.0,
        wow_rate_hz=0.27,
        wow_depth=0.0045,
        flutter_rate_hz=5.8,
        flutter_depth=0.0010,
        stereo_width=0.82,
        vinyl_noise_level_db=-56.0,
        tape_hiss_level_db=-49.0,
        atmosphere_volume_db=0.0,
        atmosphere_stereo_width=0.95,
        atmosphere_lpf_hz=11000.0,
    ),
    PresetName.vinyl_room: PresetSpec(
        name=PresetName.vinyl_room,
        hpf_hz=55.0,
        lpf_hz=7800.0,
        lpf_q=1.05,
        saturation_scale=1.08,
        tape_drive=1.00,
        tape_bias=-0.02,
        softclip_threshold=0.976,
        compression_scale=1.02,
        comp_ratio=2.35,
        comp_threshold_db=-17.0,
        comp_attack_ms=34.0,
        comp_release_ms=300.0,
        bit_depth=13,
        sample_rate_reduction_hz=30000.0,
        wow_rate_hz=0.18,
        wow_depth=0.0025,
        flutter_rate_hz=4.9,
        flutter_depth=0.0008,
        stereo_width=0.78,
        vinyl_noise_level_db=-42.0,
        tape_hiss_level_db=-60.0,
        atmosphere_volume_db=0.0,
        atmosphere_stereo_width=0.92,
        atmosphere_lpf_hz=10000.0,
    ),
    PresetName.cleaner_lofi: PresetSpec(
        name=PresetName.cleaner_lofi,
        hpf_hz=30.0,
        lpf_hz=12000.0,
        lpf_q=0.70,
        saturation_scale=0.82,
        tape_drive=0.88,
        tape_bias=0.03,
        softclip_threshold=0.993,
        compression_scale=0.78,
        comp_ratio=1.45,
        comp_threshold_db=-24.0,
        comp_attack_ms=14.0,
        comp_release_ms=160.0,
        bit_depth=16,
        sample_rate_reduction_hz=44100.0,
        wow_rate_hz=0.0,
        wow_depth=0.0,
        flutter_rate_hz=0.0,
        flutter_depth=0.0,
        stereo_width=0.95,
        vinyl_noise_level_db=-120.0,
        tape_hiss_level_db=-120.0,
        atmosphere_volume_db=0.0,
        atmosphere_stereo_width=1.0,
        atmosphere_lpf_hz=12000.0,
    ),
    PresetName.night_owl_fm: PresetSpec(
        name=PresetName.night_owl_fm,
        hpf_hz=70.0,
        lpf_hz=6900.0,
        lpf_q=1.08,
        saturation_scale=1.12,
        tape_drive=1.14,
        tape_bias=-0.10,
        softclip_threshold=0.972,
        compression_scale=1.10,
        comp_ratio=2.75,
        comp_threshold_db=-16.0,
        comp_attack_ms=38.0,
        comp_release_ms=330.0,
        bit_depth=12,
        sample_rate_reduction_hz=24000.0,
        wow_rate_hz=0.12,
        wow_depth=0.0018,
        flutter_rate_hz=6.2,
        flutter_depth=0.0012,
        stereo_width=0.72,
        vinyl_noise_level_db=-48.0,
        tape_hiss_level_db=-43.0,
        atmosphere_volume_db=0.0,
        atmosphere_stereo_width=0.88,
        atmosphere_lpf_hz=9000.0,
    ),
    PresetName.rainy_microcassette: PresetSpec(
        name=PresetName.rainy_microcassette,
        hpf_hz=45.0,
        lpf_hz=8300.0,
        lpf_q=0.82,
        saturation_scale=1.00,
        tape_drive=1.20,
        tape_bias=-0.06,
        softclip_threshold=0.979,
        compression_scale=0.98,
        comp_ratio=2.2,
        comp_threshold_db=-18.0,
        comp_attack_ms=28.0,
        comp_release_ms=260.0,
        bit_depth=13,
        sample_rate_reduction_hz=32000.0,
        wow_rate_hz=0.35,
        wow_depth=0.0060,
        flutter_rate_hz=6.5,
        flutter_depth=0.0015,
        stereo_width=0.80,
        vinyl_noise_level_db=-60.0,
        tape_hiss_level_db=-45.0,
        atmosphere_volume_db=4.0,
        atmosphere_stereo_width=0.96,
        atmosphere_lpf_hz=9500.0,
    ),
    PresetName.velvet_room: PresetSpec(
        name=PresetName.velvet_room,
        hpf_hz=33.0,
        lpf_hz=10800.0,
        lpf_q=0.74,
        saturation_scale=0.92,
        tape_drive=0.94,
        tape_bias=0.06,
        softclip_threshold=0.988,
        compression_scale=0.86,
        comp_ratio=1.75,
        comp_threshold_db=-21.0,
        comp_attack_ms=20.0,
        comp_release_ms=205.0,
        bit_depth=15,
        sample_rate_reduction_hz=40000.0,
        wow_rate_hz=0.10,
        wow_depth=0.0010,
        flutter_rate_hz=4.2,
        flutter_depth=0.0005,
        stereo_width=0.90,
        vinyl_noise_level_db=-66.0,
        tape_hiss_level_db=-58.0,
        atmosphere_volume_db=0.0,
        atmosphere_stereo_width=0.98,
        atmosphere_lpf_hz=11500.0,
    ),
    PresetName.sunrise_clean: PresetSpec(
        name=PresetName.sunrise_clean,
        hpf_hz=26.0,
        lpf_hz=14500.0,
        lpf_q=0.65,
        saturation_scale=0.74,
        tape_drive=0.78,
        tape_bias=0.08,
        softclip_threshold=0.995,
        compression_scale=0.70,
        comp_ratio=1.35,
        comp_threshold_db=-25.0,
        comp_attack_ms=12.0,
        comp_release_ms=140.0,
        bit_depth=16,
        sample_rate_reduction_hz=44100.0,
        wow_rate_hz=0.0,
        wow_depth=0.0,
        flutter_rate_hz=0.0,
        flutter_depth=0.0,
        stereo_width=0.97,
        vinyl_noise_level_db=-120.0,
        tape_hiss_level_db=-120.0,
        atmosphere_volume_db=0.0,
        atmosphere_stereo_width=1.0,
        atmosphere_lpf_hz=12500.0,
    ),
    PresetName.classic_lofi_hip_hop: PresetSpec(
        name=PresetName.classic_lofi_hip_hop,
        hpf_hz=40.0,
        lpf_hz=7500.0,
        lpf_q=0.92,
        saturation_scale=1.02,
        tape_drive=1.08,
        tape_bias=-0.03,
        softclip_threshold=0.978,
        compression_scale=1.00,
        comp_ratio=2.2,
        comp_threshold_db=-18.0,
        comp_attack_ms=26.0,
        comp_release_ms=230.0,
        bit_depth=12,
        sample_rate_reduction_hz=32000.0,
        wow_rate_hz=0.24,
        wow_depth=0.0024,
        flutter_rate_hz=5.4,
        flutter_depth=0.0007,
        stereo_width=0.85,
        vinyl_noise_level_db=-54.0,
        tape_hiss_level_db=-64.0,
        atmosphere_volume_db=0.0,
        atmosphere_stereo_width=0.94,
        atmosphere_lpf_hz=10500.0,
    ),
    PresetName.vinyl_cafe: PresetSpec(
        name=PresetName.vinyl_cafe,
        hpf_hz=30.0,
        lpf_hz=9000.0,
        lpf_q=0.88,
        saturation_scale=0.88,
        tape_drive=0.94,
        tape_bias=0.02,
        softclip_threshold=0.986,
        compression_scale=0.84,
        comp_ratio=1.7,
        comp_threshold_db=-21.0,
        comp_attack_ms=22.0,
        comp_release_ms=190.0,
        bit_depth=14,
        sample_rate_reduction_hz=36000.0,
        wow_rate_hz=0.16,
        wow_depth=0.0016,
        flutter_rate_hz=4.6,
        flutter_depth=0.0005,
        stereo_width=0.90,
        vinyl_noise_level_db=-44.0,
        tape_hiss_level_db=-70.0,
        atmosphere_volume_db=2.0,
        atmosphere_stereo_width=0.98,
        atmosphere_lpf_hz=11000.0,
    ),
    PresetName.tape_nostalgia: PresetSpec(
        name=PresetName.tape_nostalgia,
        hpf_hz=50.0,
        lpf_hz=6500.0,
        lpf_q=1.10,
        saturation_scale=1.16,
        tape_drive=1.34,
        tape_bias=-0.12,
        softclip_threshold=0.969,
        compression_scale=1.10,
        comp_ratio=2.7,
        comp_threshold_db=-16.0,
        comp_attack_ms=36.0,
        comp_release_ms=320.0,
        bit_depth=11,
        sample_rate_reduction_hz=22050.0,
        wow_rate_hz=0.32,
        wow_depth=0.0045,
        flutter_rate_hz=6.8,
        flutter_depth=0.0018,
        stereo_width=0.80,
        vinyl_noise_level_db=-70.0,
        tape_hiss_level_db=-40.0,
        atmosphere_volume_db=0.0,
        atmosphere_stereo_width=0.90,
        atmosphere_lpf_hz=8500.0,
    ),
    PresetName.rainy_study: PresetSpec(
        name=PresetName.rainy_study,
        hpf_hz=40.0,
        lpf_hz=8000.0,
        lpf_q=0.78,
        saturation_scale=0.84,
        tape_drive=0.90,
        tape_bias=0.00,
        softclip_threshold=0.989,
        compression_scale=0.98,
        comp_ratio=1.85,
        comp_threshold_db=-19.0,
        comp_attack_ms=24.0,
        comp_release_ms=210.0,
        bit_depth=15,
        sample_rate_reduction_hz=38000.0,
        wow_rate_hz=0.10,
        wow_depth=0.0010,
        flutter_rate_hz=4.0,
        flutter_depth=0.0003,
        stereo_width=0.90,
        vinyl_noise_level_db=-68.0,
        tape_hiss_level_db=-66.0,
        atmosphere_volume_db=8.0,
        atmosphere_stereo_width=1.0,
        atmosphere_lpf_hz=9200.0,
    ),
    PresetName.dusty_mpc: PresetSpec(
        name=PresetName.dusty_mpc,
        hpf_hz=60.0,
        lpf_hz=6000.0,
        lpf_q=1.12,
        saturation_scale=1.06,
        tape_drive=1.06,
        tape_bias=-0.08,
        softclip_threshold=0.975,
        compression_scale=1.04,
        comp_ratio=2.45,
        comp_threshold_db=-17.0,
        comp_attack_ms=30.0,
        comp_release_ms=250.0,
        bit_depth=10,
        sample_rate_reduction_hz=22050.0,
        wow_rate_hz=0.14,
        wow_depth=0.0015,
        flutter_rate_hz=5.2,
        flutter_depth=0.0008,
        stereo_width=0.75,
        vinyl_noise_level_db=-58.0,
        tape_hiss_level_db=-72.0,
        atmosphere_volume_db=0.0,
        atmosphere_stereo_width=0.90,
        atmosphere_lpf_hz=9000.0,
    ),
}


def get_preset(preset_name: PresetName) -> PresetSpec:
    return PRESETS[preset_name]
